### ISSUE TITLE
Can't add plugins to People

### ISSUE THREAD

**Issue by spacedman** [evildmp/Arkestra#10]
got the latest arkestra from git. Running using the instructions I blogged last week. Create a Page, an Entity, a Site, a Building, all okay, enough to create a Person now. So enter details and save. Now try adding a text/layout or any other plugin to the Description slot and the 'Add Plugin' link is doing nothing - not even a request to the server.

Similar widgets work fine in the Building dialog.

Three Javascript errors on the console:
- "$.ui is undefined" in ui.sortable 
- "$.widget is not a function" in ui.combobox. 
- "$.fn.cmsPatchCSRF is not a function" in plugin_editor.js 

No console errors at all from the Building modify page which has three plugin editors.

**Comment by evildmp** [comment]
Can you add plugins to placeholders on other models? If so, looks like some silly admin issue on People. I will try to check later, but I might not be able to.

**Comment by spacedman** [comment]
Yes, I can go to Buildings, choose one of my buildings, and I can add things to Description, Getting Here, and Access and Parking.

**Comment by luxumbra** [comment]
I have tried the process spacedman has followed and can not reproduce the error. This was done on the latest code pulled from git this evening.

**Comment by spacedman** [comment]
Did you use the same installation procedure for django and all the packages via pip and/or git? I think this might be a subtle jquery problem.

**Comment by luxumbra** [comment]
No, i had django, etc already installed from a previous build of Arkestra. I have had issues in the past with paths for jquery, etc when using the autocomplete inputs in admin. FWIW, i used pip for installing my packages on Ubuntu 10.04 LTS.

**Comment by spacedman** [comment]
I'm going to try and track down this today. I think its important for an application with so many layers of dependency to get this right. 

For what its worth I had a quick try of Arkestra with the latest git checkout of django-cms, but that is using the shiny django-sekizai block tags and various other features that broke me. Anyway, back to JS inspection.

**Comment by spacedman** [comment]
I think its to do with the PersonAdmin form loading multiple copies of jquery from various places. I'm not sure where its getting it all from, possibly related to the AutocompleteMixin which it gets...

**Comment by spacedman** [comment]
Nope. It is the jquery.js added by the django-widgetry FkLookup widget.  If I comment-out '/media/cms/js/lib/jquery.js' from the Media class then the Person plugin controls all work. Uncomment it, and it breaks as described.

Not sure what the proper fix is. Installed as decribed, I see three jquery.js files in different places...

**Comment by evildmp** [comment]
I think the problem is the version of widgetry. Please use the version at https://github.com/evildmp/django-widgetry - if that helps, let me know.
