### ISSUE TITLE
autocomplete fails if page has no description metadata

### ISSUE THREAD

**Issue by spacedman** [evildmp/Arkestra#14]
Create a page with nothing in the SEO description meta field. Create an entity for that page. Try to create a member list for that entity's members as a plugin in that page. The autocomplete fails with:

Something went wrong while handling a search wrapper: 'NoneType' object has no attribute 'get_meta_description'

**Comment by evildmp** [comment]
This has been fixed, but we still need to find a way to alert users when there are items with inadequate metdata
