### ISSUE TITLE
Links from people to files not working properly

### ISSUE THREAD

**Issue by spacedman** [evildmp/Arkestra#19]
If I make a Link in the Links section of a Person to an object of type filer:file and choose an image then in the person's page in the contacts list it shows up as "no heading defined"  (if I link to a CMS page it says "related pages").

The filename appears as an HTML link but the href goes to the current page, not to the object.

I'm haven't looked to see if this is a problem with all the other link types - page and person links work well, file doesn't.

**Comment by evildmp** [comment]
Fixed, I hope; please report any further problems
