### ISSUE TITLE
no such table: news_and_events_event_publishing_destinations

### ISSUE THREAD

**Issue by lynx-r** [evildmp/Arkestra#21]
Hello,

When i do ./manage.py migrate i get error django.db.utils.DatabaseError: no such table: news_and_events_event_publishing_destinations
Complete log https://gist.github.com/1547567

Any idea?

**Comment by evildmp** [comment]
On Sun, Jan 1, 2012, lynx-r <reply+i-2697356-07a95d356462494ce8479afba793b9685fac1c4a-86222@reply.github.co> wrote:

> When i do ./manage.py migrate i get error django.db.utils.DatabaseError:
> no such table: news_and_events_event_publishing_destinations
> Complete log https://gist.github.com/1547567

If you are not actually migrating from an old database, I would simply disable south for the time being, and use syncdb. I am afraid the migrations are quite a mess at the moment. I will be clearing them all out soon, and starting from scratch. Let me know if that helps. Also, give me a shout on #arkestra on irc.freenode.net if you need more help.

**Comment by lynx-r** [comment]
Thank you, this helped.

**Comment by evildmp** [comment]
By the way - are you still experimenting with Arkestra/Django CMS?

Regards,

Daniele

**Comment by lynx-r** [comment]
Just looking at it.
