### ISSUE TITLE
Issue when editing and persons existing Description (text/layout)

### ISSUE THREAD

**Issue by luxumbra** [evildmp/Arkestra#3]
'Person' object has no attribute 'get_website'

Full traceback is here: http://pastie.org/private/sggmugvmjkzw0116uwxiwg

This is fine when adding a description using the text/layout plugin but occurs if going back in to edit after it's been saved.

**Comment by evildmp** [comment]
This was actually a Semantic Editor issue (now resolved) but still, Person needs a get_website() method - will do that.
