### ISSUE TITLE
'js' is not a valid tag library

### ISSUE THREAD

**Issue by konr4d** [evildmp/Arkestra#41]
I get this error while trying to list records in Entity, ExternalSite and Event admin. It may be a misconfiguration or I lack some library but I haven't been able to locate what's the problem.

Environment:

Request Method: GET
Request URL: http://localhost:8000/_a/contacts_and_people/entity/

Django Version: 1.4
Python Version: 2.7.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.humanize',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'django.contrib.flatpages',
 'south',
 'cms',
 'mptt',
 'menus',
 'sekizai',
 'cms.plugins.file',
 'cms.plugins.picture',
 'cms.plugins.teaser',
 'cms.plugins.text',
 'cms.plugins.video',
 'cms.plugins.twitter',
 'arkestra_utilities',
 'contacts_and_people',
 'vacancies_and_studentships',
 'news_and_events',
 'links',
 'arkestra_utilities.widgets.combobox',
 'arkestra_image_plugin',
 'video',
 'housekeeping',
 'polymorphic',
 'semanticeditor',
 'easy_thumbnails',
 'typogrify',
 'filer',
 'widgetry',
 'sieci_cms.news',
 'sieci_cms.people',
 'sieci_cms.projects')
Installed Middleware:
('django.middleware.gzip.GZipMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
 'cms.middleware.multilingual.MultilingualURLMiddleware',
 'cms.middleware.page.CurrentPageMiddleware',
 'cms.middleware.user.CurrentUserMiddleware',
 'cms.middleware.toolbar.ToolbarMiddleware')

Template error:
In template /home/konrad/work/pjwstk/sieci_cms/libs/contacts_and_people/templates/admin/contacts_and_people/entity/change_list.html, error at line 2
   'js' is not a valid tag library: Template library js not found, tried django.templatetags.js,django.contrib.admin.templatetags.js,django.contrib.humanize.templatetags.js,django.contrib.flatpages.templatetags.js,cms.templatetags.js,mptt.templatetags.js,menus.templatetags.js,sekizai.templatetags.js,arkestra_utilities.templatetags.js,contacts_and_people.templatetags.js,vacancies_and_studentships.templatetags.js,news_and_events.templatetags.js,links.templatetags.js,housekeeping.templatetags.js,easy_thumbnails.templatetags.js,typogrify.templatetags.js,filer.templatetags.js
   1 : {% extends "admin/change_list.html" %}
   2 :  {% load adminmedia admin_list i18n cms_admin js %} 
   3 : {% block title %}List of entities{% endblock %}
   4 : {% block bodyclass %}change-list{% endblock %}
   5 : 
   6 : {% if not is_popup %}{% block breadcrumbs %}
   7 :     <div class="breadcrumbs">
   8 :     <a href="../../">{% trans "Home" %}</a> &rsaquo; 
   9 :     <a href="../">{{ app_label|capfirst|escape }}</a> &rsaquo; {{ opts.verbose_name_plural|capfirst|escape }}
   10 :     </div>
   11 : {% endblock %}{% endif %}
   12 : 

Traceback:
File "/home/konrad/work/pjwstk/sieci_cms/libs/django/core/handlers/base.py" in get_response
1.                     response = response.render()
   File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/response.py" in render
2.             self._set_content(self.rendered_content)
   File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/response.py" in rendered_content
3.         template = self.resolve_template(self.template_name)
   File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/response.py" in resolve_template
4.             return loader.get_template(template)
   File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/loader.py" in get_template
5.     template, origin = find_template(template_name)
   File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/loader.py" in find_template
6.             source, display_name = loader(name, dirs)
   File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/loader.py" in **call**
7.         return self.load_template(template_name, template_dirs)
   File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/loaders/cached.py" in load_template
8.             template, origin = self.find_template(template_name, template_dirs)
   File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/loaders/cached.py" in find_template
9.                 template, display_name = loader(name, dirs)
   File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/loader.py" in **call**
10.         return self.load_template(template_name, template_dirs)
    File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/loader.py" in load_template
11.             template = get_template_from_string(source, origin, template_name)
    File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/loader.py" in get_template_from_string
12.     return Template(source, origin, name)
    File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/base.py" in **init**
13.         self.nodelist = compile_string(template_string, origin)
    File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/base.py" in compile_string
14.     return parser.parse()
    File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/base.py" in parse
15.                     compiled_result = compile_func(self, token)
    File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/loader_tags.py" in do_extends
16.     nodelist = parser.parse()
    File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/base.py" in parse
17.                     compiled_result = compile_func(self, token)
    File "/home/konrad/work/pjwstk/sieci_cms/libs/django/template/defaulttags.py" in load
18.                                           (taglib, e))

Exception Type: TemplateSyntaxError at /_a/contacts_and_people/entity/
Exception Value: 'js' is not a valid tag library: Template library js not found, tried django.templatetags.js,django.contrib.admin.templatetags.js,django.contrib.humanize.templatetags.js,django.contrib.flatpages.templatetags.js,cms.templatetags.js,mptt.templatetags.js,menus.templatetags.js,sekizai.templatetags.js,arkestra_utilities.templatetags.js,contacts_and_people.templatetags.js,vacancies_and_studentships.templatetags.js,news_and_events.templatetags.js,links.templatetags.js,housekeeping.templatetags.js,easy_thumbnails.templatetags.js,typogrify.templatetags.js,filer.templatetags.js

**Comment by evildmp** [comment]
On Tue, Jul 10, 2012, Konrad Adamczyk <reply+i-5531687-c1c4beae5e813c089cbe9c9b3e6f473357129f35-86222@reply.github.co> wrote:

> I get this error while trying to list records in Entity, ExternalSite
> and Event admin. It may be a misconfiguration or I lack some library but
> I haven't been able to locate what's the problem.

Thanks for the report, I think it's that if you use the pip branch from GitHub you won't get this error.

In fact that's definitely the branch to use.

**Comment by konr4d** [comment]
Thank you for the response. I managed to work around it by removing js from the load templatetag in admin/contacts_and_people/entity/change_list.html.

**Comment by evildmp** [comment]
OK - thanks for the report, there was indeed an issue, but it's now fixed in the _develop_ branch. In django CMS, what used to be called "js" is now called "cms_js_tags" - I was sure that had been pushed to the repository, but somehow not. Sorry about that.
