### ISSUE TITLE
Title update problem

### ISSUE THREAD

**Issue by darbula** [evildmp/Arkestra#68]
When title abbreviation is updated it breaks [referential integrity](http://en.wikipedia.org/wiki/Referential_integrity) and all Person with that title are no longer accessible in frontend and backend.

**Comment by evildmp** [comment]
This is going to be messy. It will require:
- schema migration to:
  - rename `title` to `temporary_title`
  - add a new `title` field without `to_field` on it
- data migration to populate the new field with primary keys based on existing `temporary_title` field
- schema migration to delete `temporary_title`
