### ISSUE TITLE
example_14 fails during loaddata step

### ISSUE THREAD

**Issue by easp** [evildmp/Arkestra#72]
I'm trying to get the example for django 1.4 running using the installation instructions [here](https://arkestra.readthedocs.org/en/latest/getting_started/installation.html). 

It fails when loading the sample data:

```
(env_mycms)eas:example_14 eas$ ./manage.py loaddata example_database.json
Problem installing fixture 'example_database.json': Traceback (most recent call last):
  File "/Users/eas/Prj/repos/mycms/env_mycms/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 190, in handle
    for obj in objects:
  File "/Users/eas/Prj/repos/mycms/env_mycms/lib/python2.7/site-packages/django/core/serializers/json.py", line 47, in Deserializer
    raise DeserializationError(e)
DeserializationError: Page has no field named u'page_flags'
```

Near as I can tell, the problem is that the instructions install the cannonical version of django-cms, but the sample data includes page_flags which are only supported by evildmp/django-cms's fork.

I'm assuming that I can figure out how to install the evildmp/django-cms fork instead and everything will work, but I'm filing this issue, in part, so that it is documented for others to see.

**Comment by evildmp** [comment]
Sorry, my mistake, it looks like I dumped the dataset from a version that included my PageFlags patch of django CMS last week. I'll correct that later this morning.

**Comment by evildmp** [comment]
I've pushed the correct `example_database.json`. Thanks for the report, please try again, and let me know if you run into any other problems.

**Comment by easp** [comment]
Thanks, the new fixture works!
