### ISSUE TITLE
Tree admin exception on news and events admin page

### ISSUE THREAD

**Issue by darbula** [evildmp/Arkestra#75]
When loading news and events change list in admin `/admin/news_and_events/event/` django raises following Exception:

```
Exception Type: TypeError
Exception Value: 'unicode' object is not callable
...env\lib\site-packages\treeadmin\admin.py in indented_short_title
            r += item.short_title() 
```

It seems that treeadmin is expecting callable for short_title and in arkestra models short_title is unicode.

**Comment by evildmp** [comment]
On Thu, Mar 28, 2013, darbula notifications@github.com wrote:

> When loading news and events change list in admin `/admin/
> news_and_events/event/` django raises following Exception:
> 
>    Exception Type:    TypeError
>    Exception Value: 'unicode' object is not callable
>    ...env\lib\site-packages\treeadmin\admin.py in indented_short_title
>                r += item.short_title() 
> 
> It seems that treeadmin is expecting callable for short_title and in
> arkestra models short_title is unicode.

I had to patch treeadmin for this.

https://github.com/evildmp/django-treeadmin

I made a pull request to piquadrat for it, and REQUIREMENTS.txt should have picked up my fork:

https://github.com/evildmp/Arkestra/blob/develop/REQUIREMENTS.txt#L11

Sorry for the inconvenience.

Daniele

**Comment by darbula** [comment]
Ah sorry on one computer I have installed form your fork, but on the other form the piquadrat's. Now it works.
