### ISSUE TITLE
"No module named functions"

### ISSUE THREAD

**Issue by spacedman** [evildmp/Arkestra#9]
Doing a syncdb from scratch:

 File "/home/rowlings/Web/CMS/Arkestra/Envs/Aug1/src/arkestra/contacts_and_people/models.py", line 700, in <module>
    from news_and_events.functions import get_news_and_events
ImportError: No module named functions

Looks like trying to get something you've now put in defunct_functions.py in news_and_events.

**Comment by evildmp** [comment]
Pretty sure that shouldn't be an issue - all references to functions.py should have gone by now. If not, just rename defunct_functions for the time being till I get back.

**Comment by evildmp** [comment]
Oops. That import should not have been there. Sorry.
